# Generated by Django 3.2.6 on 2021-08-03 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_scrape_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrape',
            name='date',
        ),
        migrations.RemoveField(
            model_name='scrape',
            name='time',
        ),
        migrations.AddField(
            model_name='scrape',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
